blank_issues_enabled: false
contact_links:
    - name: Suggestion or feature request
      url: https://github.com/runelite/runelite/discussions/categories/ideas
      about: Got an idea of something which should be changed or added? Search for or start a new discussion!
    - name: Help
      url: https://github.com/runelite/runelite/discussions/categories/q-a
      about: Need support or think you've encountered a bug? Check the Q&A section!
